import uuid from 'uuid';
const productsArray = [
    // OFFICIAL MD
    {
        id: uuid(),
        item: "OFFICIAL LIGHT STICK Ver.3",
        category: "official_md",
        price: "29.10",
        src: "bts_official_light_stick_v3",
        description: "SIZE:\n224 X 98 X 98\n\nMATERIAL:\nABS / PC / SILICON\n\nCONTENTS:\nLight Stick, Straps, Nonwoven bags, User manual, Quality Guarantee Card\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "OFFICIAL LIGHT FINGER RING",
        category: "official_md",
        price: "13.20",
        src: "official_light_finger_ring",
        description: "SIZE:\n30 X 55\n\nMATERIAL:\nABS / PC / STEEL\n\nCONTENTS:\nIncluded 2 mercury batteries\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "OFFICIAL LIGHT STICK CASE",
        category: "official_md",
        price: "17.60",
        src: "official_light_stick_case",
        description: "SIZE:\n111 X 244 (CASE)\n1400 (STRAP)\n\nMATERIAL:\nPU / EVA\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "OFFICIAL SLOGAN",
        category: "official_md",
        price: "15.90",
        src: "official_slogan",
        description: "SIZE:\n850 X 200\n\nMATERIAL:\nPOLYSETER / POLYAMIDE\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    // TOUR MD
    {
        id: uuid(),
        item: "PORTABLE CHARGER",
        category: "tour_md",
        price: "30.80",
        src: "portable_charger",
        description: "SIZE:\n75 X 130\n\nMATERIAL:\nABS / PC\n\nCONTENTS:\n10000mAh\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BOTTLE",
        category: "tour_md",
        price: "17.60",
        src: "bottle",
        description: "SIZE:\n65 X 210 450ml\n\nMATERIAL:\nAS / PP\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "SLIPPER",
        category: "tour_md",
        price: "30.80",
        src: "slipper",
        description: "SIZE:\nS (230-240)\nM (245-255)\nL (260-270)\n\nMATERIAL:\nPOLYURETHANE / PU\n\nCONTENTS:\nIncluded a non-woven bag\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "METAL BADGE SET",
        category: "tour_md",
        price: "13.20",
        src: "metal_badge_set",
        description: "SIZE:\n25 X 25\n\nMATERIAL:\nMETAL\n\nCONTENTS:\n2ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "MAGNET",
        category: "tour_md",
        price: "6.20",
        src: "magnet",
        description: "SIZE:\n60 X 80 (STAND)\n35 X 50 (MAGNET)\n\nMATERIAL:\nMAGNET / PAPER\n\nCONTENTS:\nIncluded a magnet stand\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "SHOPPER BAG",
        category: "tour_md",
        price: "4.40",
        src: "shopper_bag",
        description: "SIZE:\n450 X 370\n\nMATERIAL:\nNON-WOVEN FABRIC\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "LUGGAGE TAG",
        category: "tour_md",
        price: "22.00",
        src: "luggage_tag",
        description: "SIZE:\n50 X 153 (TAG)\n35 X 60 (PHOTO)\n\nMATERIAL:\nLEATHER / METAL\n\nCONTENTS:\nIncluded 7 photocards\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "SMART RING",
        category: "tour_md",
        price: "15.00",
        src: "smart_ring",
        description: "SIZE:\n30 X 30\n\nMATERIAL:\nPOLYCARBONATE / ZINC\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PHONE CASE",
        category: "tour_md",
        price: "24.70",
        src: "phone_case",
        description: "SIZE:\n56 X 125\n\nMATERIAL:\nPOLYCARBONATE / PU / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "TATTOO STICKER SET",
        category: "tour_md",
        price: "7.10",
        src: "tattoo_sticker_set",
        description: "SIZE:\n130 X 90 (1SHEET)\n\nMATERIAL:\nPAPER\n\nCONTENTS:\n2sheet 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "MINI BAG",
        category: "tour_md",
        price: "24.70",
        src: "mini_bag",
        description: "SIZE:\n145 X 185\n\nMATERIAL:\nCOTTON / PU\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "ECO BAG",
        category: "tour_md",
        price: "30.80",
        src: "eco_bag",
        description: "SIZE:\n375 X 385\n\nMATERIAL:\nCOTTON / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "WRIST BAND SET",
        category: "tour_md",
        price: "13.20",
        src: "wrist_band_set",
        description: "SIZE:\n75 X 70 (1EA)\n\nMATERIAL:\nCOTTON / POLYESTER / NYLON\n\nCONTENTS:\n2ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BALL CAP",
        category: "tour_md",
        price: "26.40",
        src: "ball_cap",
        description: "SIZE:\nFREE\n\nMATERIAL:\nCOTTON 100%\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "GARLAND",
        category: "tour_md",
        price: "13.20",
        src: "garland",
        description: "SIZE:\n120 X 130 (PAPER)\n2500 (STRING)\n\nMATERIAL:\nPAPER / COTTON / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "MINI FLAG",
        category: "tour_md",
        price: "7.10",
        src: "mini_flag",
        description: "SIZE:\n60 X 165\n\nMATERIAL:\nACRYLIC / POLYESTER / ABS\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BOX TAPE SET",
        category: "tour_md",
        price: "13.20",
        src: "box_tape_set",
        description: "SIZE:\n15 X 40000\n35 X 40000\n\nMATERIAL:\nOPP\n\nCONTENTS:\n2ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "LENTICULAR L-HOLDER SET",
        category: "tour_md",
        price: "10.60",
        src: "lenticular_l_holder_set",
        description: "SIZE:\n110 X 158\n\nMATERIAL:\nPET\n\nCONTENTS:\n3ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "KEYRING",
        category: "tour_md",
        price: "15.90",
        src: "keyring",
        description: "SIZE:\n35 X 130 (LENGTH)\n20 X 20 (CHARM)\n\nMATERIAL:\nPU / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PROGRAM BOOK",
        category: "tour_md",
        price: "20.30",
        src: "program_book",
        description: "SIZE:\n200 X 270\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "ACRYLIC BADGE",
        category: "tour_md",
        price: "4.40",
        src: "acrylic_badge",
        description: "SIZE:\n35 X 42\n\nMATERIAL:\nACRYLIC\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BRACELET",
        category: "tour_md",
        price: "11.50",
        src: "bracelet",
        description: "SIZE:\n18 X 18 (CHARM)\n370 (LENGTH)\n\nMATERIAL:\nMETAL / COTTON\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BANDANA",
        category: "tour_md",
        price: "17.60",
        src: "bandana",
        description: "SIZE:\n600 X 600 (BANDANA)\n86 X 25 (LEATHER RING)\n\nMATERIAL:\nCOTTON / LEATHER\n\nCONTENTS:\nIncluded a leather ring\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "T-SHIRT [BLACK]",
        category: "tour_md",
        price: "30.80",
        src: "t_shirt_black",
        description: "SIZE:\nM: 470 X 220 X 680\nL: 540 X 230 X 720\n\nMATERIAL:\nCOTTON 100%\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "T-SHIRT [IVORY]",
        category: "tour_md",
        price: "30.80",
        src: "t_shirt_ivory",
        description: "SIZE:\nM: 470 X 220 X 680\nL: 540 X 230 X 720\n\nMATERIAL:\nCOTTON 100%\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "TOWEL",
        category: "tour_md",
        price: "15.90",
        src: "towel",
        description: "SIZE:\n800 X 350\n\nMATERIAL:\nCOTTON 100%\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "FABRIC POSTER",
        category: "tour_md",
        price: "28.20",
        src: "fabric_poster",
        description: "SIZE:\n620 X 620\n\nMATERIAL:\nPOLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "DECO STICKER SET",
        category: "tour_md",
        price: "10.60",
        src: "deco_sticker_set",
        description: "SIZE:\n80 X 90 (1ea)\n\nMATERIAL:\nPAPER\n\nCONTENTS:\n18ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "IMAGE PICKET",
        category: "tour_md",
        price: "7.10",
        src: "image_picket",
        description: "SIZE:\n295 X 435\n\nMATERIAL:\nPP\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PREMIUM PHOTO",
        category: "tour_md",
        price: "8.00",
        src: "premium_photo",
        description: "SIZE:\n240 X 340\n\nMATERIAL:\nPAPER / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "POSTER SET",
        category: "tour_md",
        price: "17.60",
        src: "poster_set",
        description: "SIZE:\n520 X 740\n\nMATERIAL:\nPAPER\n\nCONTENTS:\n7ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "MINI PHOTO CARD",
        category: "tour_md",
        price: "6.20",
        src: "mini_photo_card",
        description: "SIZE:\n70 X 100 (1ea)\n\nMATERIAL:\nPAPER\n\nCONTENTS:\nRandom 8ea 1set\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    //EXHIBITION
    {
        id: uuid(),
        item: "KEYRING [LOGO ver.]",
        category: "exhibition",
        price: "13.20",
        src: "keyring_logo_ver",
        description: "SIZE:\n32.5 X 156 (length)\n33 X 53 (acrylic)\n\nMATERIAL:\nACRYLIC / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "KEYRING [BTS ver.]",
        category: "exhibition",
        price: "15.90",
        src: "keyring_bts_ver",
        description: "SIZE:\n32.5 X 156 (length)\n33 X 53 (acrylic)\n\nMATERIAL:\nACRYLIC / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PIN BADGE",
        category: "exhibition",
        price: "7.10",
        src: "pin_badge",
        description: "SIZE:\n20 X 20\n\nMATERIAL:\nMETAL\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "HAND MIRROR",
        category: "exhibition",
        price: "10.60",
        src: "hand_mirror",
        description: "SIZE:\n58 X 58\n\nMATERIAL:\nPU / GLASS\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "TOWEL",
        category: "exhibition",
        price: "11.50",
        src: "towel",
        description: "SIZE:\n400 X 800\n\nMATERIAL:\nCOTTON\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "STICKER",
        category: "exhibition",
        price: "0.90",
        src: "sticker",
        description: "SIZE:\n50 X 50\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "MASKING TAPE",
        category: "exhibition",
        price: "5.30",
        src: "masking_tape",
        description: "SIZE:\n20 X 10\n\nMATERIAL:\nWASHI (PAPER)\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "LETTER PAPER SET",
        category: "exhibition",
        price: "6.20",
        src: "letter_paper_set",
        description: "SIZE:\n257 X 182\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "NOTEBOOK SET",
        category: "exhibition",
        price: "8.00",
        src: "notebook_set",
        description: "SIZE:\n150 X 210 (note)\n150 X 210 X 9 (sleeve)\n\nMATERIAL:\nPAPER / PET\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "JELL PEN",
        category: "exhibition",
        price: "4.40",
        src: "jell_pen",
        description: "SIZE:\n10 X 140\n\nMATERIAL:\nABS / PVC\n\nMADE IN CHINA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "CAN BADGE",
        category: "exhibition",
        price: "2.70",
        src: "can_badge",
        description: "SIZE:\nØ30\n\nMATERIAL:\nMETAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "ROLL POUCH",
        category: "exhibition",
        price: "14.10",
        src: "roll_pouch",
        description: "SIZE:\n285 X 210 (pouch)\n530 (strap)\n\nMATERIAL:\nCOTTON / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "ECO BAG",
        category: "exhibition",
        price: "17.60",
        src: "eco_bag",
        description: "SIZE:\n380 X 430\n\nMATERIAL:\nCOTTON / POLYESTER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "T-SHIRT",
        category: "exhibition",
        price: "28.20",
        src: "t_shirt",
        description: "SIZE:\n470 X 220 X 680\n\nMATERIAL:\nCOTTON 100%\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PHOTO FRAME",
        category: "exhibition",
        price: "13.20",
        src: "photo_frame",
        description: "SIZE:\n102 X 152\n\nMATERIAL:\nALUMINIUM\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BOOKMARK",
        category: "exhibition",
        price: "6.20",
        src: "bookmark",
        description: "SIZE:\n60 X 120\n\nMATERIAL:\nPAPER / PET\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "CLIP BOARD",
        category: "exhibition",
        price: "10.60",
        src: "clip_board",
        description: "SIZE:\n220 X 317 (board)\n70 X 100 (photo card)\n\nMATERIAL:\nPAPER / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "POSTER",
        category: "exhibition",
        price: "7.10",
        src: "poster",
        description: "SIZE:\n420 X 600\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "PUZZLE",
        category: "exhibition",
        price: "22.00",
        src: "puzzle",
        description: "SIZE:\n250 X 340 (puzzle)\nØ137 (tin)\n\nMATERIAL:\nPAPER / TIN\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "POSTCARD SET",
        category: "exhibition",
        price: "13.20",
        src: "postcard_set",
        description: "SIZE:\n100 X 150\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    // DVD
    {
        id: uuid(),
        item: "BTS 4th MUSTER BLU-RAY",
        category: "dvd",
        price: "48.40",
        src: "bts_4th_muster_blu_ray",
        description: "PACKAGE:\nOUTBOX\n3DISC DIGIPAK\nPHOTOBOOK(16P)\nEMBOSSING STICKER(1EA)\n\nDURATION:\nDISC 01: APPROX 80 MINS\nDISC 02: APPROX 106 MINS\nDISC 03: APPROX 110 MINS\n\nSUBTITLES:\nKOREAN, ENGLISH, CHINESE\n\nVIDEO:\n1080i / 1.78:1 Wide screen / Color / AVC\n\nAUDIO:\nKorean DTS-HD MASTER AUDIO 2.0 (48KHz/24bit)",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "BTS 4th MUSTER DVD",
        category: "dvd",
        price: "37.90",
        src: "bts_4th_muster_dvd",
        description: "PACKAGE:\nOUTBOX\n3DISC DIGIPAK\nPHOTOBOOK(144P)\nPOSTCARD(1EA)\nPHOTOCARD(RANDOM 1EA)\n\nDURATION:\nDISC 01: APPROX 80 MINS\nDISC 02: APPROX 106 MINS\nDISC 03: APPROX 110 MINS\n\nSUBTITLES:\nKOREAN, ENGLISH, CHINESE\n\nASPECT:\nNTSC 16:9 WIDE SCREEN COLOR\n\nAUDIO:\nDOLBY DIGITAL STEREO",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },
    {
        id: uuid(),
        item: "2018 BTS SUMMER PACKAGE",
        category: "dvd",
        price: "37.00",
        src: "2018_bts_summer_package",
        description: "PACKAGE:\nPHOTOBOOK(196P)\nGUIDE BOOK (20P)\nMINI POSTER 1set (7ea)\nSTRAP (1ea)\nTRAVEL TOPPER (1ea)\n\nDURATION:\nDISC: ABOUT 95 MINS",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: ""
    },










    // ALBUMS
    {
        id: uuid(),
        item: "LOVE YOURSELF 結 ‘Answer’",
        category: "albums",
        price: "14.90",
        src: "ly_answer",
        description: "TRACK LIST:\n\nCD1\n1. Euphoria\n2. Trivia 起 : Just Dance\n3. Serendipity (Full Length Edition)\n4. DNA\n5. 보조개\n6. Trivia 承 : Love\n7. Her\n8. Singularity\n9. FAKE LOVE\n10. 전하지 못한 진심 (Feat. Steve Aoki)\n11. Trivia 轉 : Seesaw\n12. Tear\n13. Epiphany\n14. I'm Fine\n15. IDOL\n16. Answer : Love Myself\n\nCD2\n1. Magic Shop\n2. Best Of Me\n3. Airplane pt.2\n4. 고민보다 Go\n5. Anpanman\n6. MIC Drop\n7. DNA (Pedal 2 LA Mix)\n8. FAKE LOVE (Rocking Vibe Mix)\n9. MIC Drop (Steve Aoki Remix) (Full Length Edition)",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "LOVE YOURSELF 轉 'Tear'",
        category: "albums",
        price: "14.90",
        src: "ly_tear",
        description: "TRACK LIST:\n\n1. Intro : Singularity\n2. FAKE LOVE\n3. 전하지 못한 진심 (Feat. Steve Aoki)\n4. 134340\n5. 낙원\n6. Love Maze\n7. Magic Shop\n8. Airplane pt.2\n9. Anpanman\n10. So What\n11. Outro : Tear",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "LOVE YOURSELF 承 'Her'",
        category: "albums",
        price: "59.60",
        src: "ly_her",
        description: "TRACK LIST:\n\n1. Intro : Serendipity\n2. DNA\n3.Best Of Me\n4.보조개\n5.Pied Piper\n6.Skit : Billboard Music Awards Speech\n7.MIC Drop\n8.고민보다 Go\n9.Outro : Her\n+2 Hidden Tracks",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "YOU NEVER WALK ALONE",
        category: "albums",
        price: "17.80",
        src: "ynwa",
        description: "TRACK LIST:\n\n1. Intro : Boy Meets Evil\n2. 피 땀 눈물\n3. Begin Lie Stigma\n4. First Love\n5. Reflection\n6. MAMA\n7. Awake\n8. Lost\n9. BTS Cypher 4\n10. Am I Wrong\n11. 21세기 소녀 둘! 셋! (그래도 좋은 날이 더 많기를)\n12. 봄날\n13. Not Today\n14. Outro : Wings\n15. A Supplementary Story : You Never Walk Alone",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "WINGS",
        category: "albums",
        price: "14.90",
        src: "wings",
        description: "TRACK LIST:\n\n1. Intro : Boy Meets Evil\n2. 피 땀 눈물\n3. Begin\n4. Lie\n5. Stigma\n6. First Love\n7. Reflection\n8. MAMA\n9. Awake\n10. Lost\n11. BTS Cypher 4\n12. Am I Wrong\n13. 21세기 소녀\n14. 둘! 셋! (그래도 좋은 날이 더 많기를)\n15. Interlude : Wing",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "화양연화 'Young Forever'",
        category: "albums",
        price: "18.80",
        src: "tbmil_yf",
        description: "TRACK LIST:\n\nCD1\n1. Intro : 화양연화\n2. I NEED U\n3. 잡아줘 (Hold me tight)\n4. 고엽\n5. Butterfly (Prologue mix)\n6. RUN\n7. Ma City\n8. 뱁새\n9. 쩔어\n10. 불타오르네 (FIRE)\n11. Save ME\n12. EPILOGUE : Young Forever\n\nCD2\n1. Converse High\n2. 이사\n3. Whalien 52\n4. Butterfly\n5. House Of Cards (Full length edition)\n6. Love is not over (Full length edition)\n7. I NEED U (Urban mix)\n8. I NEED U (Remix)\n9. RUN ballad mix\n10. RUN (Alternative mix)\n11. Butterfly (Alternative mix)",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "화양연화 Pt.2",
        category: "albums",
        price: "12.10",
        src: "tbmil_2",
        description: "TRACK LIST:\n\n1. Intro : Never Mind\n2. RUN\n3. Butterfly\n4. Whalien 52\n5. Ma City\n6. 뱁새\n7. SKIT : One night in a strange city\n8. 고엽\n9.OUTRO : House Of Cards",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "화양연화 Pt.1",
        category: "albums",
        price: "12.10",
        src: "tbmil_1",
        description: "TRACK LIST:\n\n1. Intro : 화양연화\n2. I NEED U\n3. 잡아줘 (Hold Me Tight)\n4. SKIT : Expectation!\n5. 쩔어\n6. 흥탄소년단\n7. Converse High\n8. 이사\n9. Outro : Love is Not Over",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "Dark & Wild",
        category: "albums",
        price: "13.50",
        src: "dark_wild",
        description: "TRACK LIST:\n\n1. Intro: What am I to you\n2. Danger\n3. 호르몬 전쟁\n4. 힙합성애자\n5. Let Me Know\n6. Rain\n7. BTS Cypher PT.3 : KILLER (Feat. Supreme Boi)\n8. Interlude : 뭐해\n9. 핸드폰 좀 꺼줄래\n10. 이불킥\n11. 24/7=heaven\n12. 여기 봐\n13. 2학년\n14. Outro: 그게 말이 돼?",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "Skool Luv Affair",
        category: "albums",
        price: "10.80",
        src: "skool_luv_affair",
        description: "TRACK LIST:\n\n1. Intro: Skool Luv Affair\n2. 상남자 (Boy In Luv)\n3. Skit: Soulmate\n4. 어디에서 왔는지\n5. 하루만\n6. Tomorrow\n7. BTS Cypher PT.2: Triptych\n8. 등골브레이커\n9. JUMP\n10. Outro: Propose",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "O!RUL8,2?",
        category: "albums",
        price: "10.80",
        src: "orul82",
        description: "TRACK LIST:\n\n1. Intro : O!RUL8,2?\n2. N.O\n3. We On\n4. Skit : R U Happy Now?\n5. If I Ruled The World\n6. Coffee\n7. BTS Cypher PT.1\n8. 진격의 방탄\n9. 팔도강산\n10. OUTRO : LUV IN SKOOL",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "2 COOL 4 SKOOL",
        category: "albums",
        price: "9.40",
        src: "2cool4skool",
        description: "TRACK LIST:\n\n1. Intro : 2 COOL 4 SKOOL (Feat. DJ Friz)\n2. We are bulletproof PT.2\n3. Skit : Circle room talk\n4. No More Dream\n5. Interlude\n6. 좋아요\n7. Outro: Circle room cipher",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    // LOVE MYSELF
    {
        id: uuid(),
        item: "POUCH",
        category: "love_myself",
        price: "26.00",
        src: "pouch_lm",
        description: "SIZE:\n145 X 185\n\nMATERIAL:\nCOTTON / PU\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "KEYRING",
        category: "love_myself",
        price: "20.00",
        src: "keyring_lm",
        description: "SIZE:\n35 X 130 (length)\n20 X 20 (charm)\n\nMATERIAL:\nPU / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "STICKER",
        category: "love_myself",
        price: "6.00",
        src: "sticker_lm",
        description: "SIZE:\n25 X 25\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "NOTEBOOK",
        category: "love_myself",
        price: "9.00",
        src: "notebook_lm",
        description: "SIZE:\n200 X 270\n\nMATERIAL:\nPAPER\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    },
    {
        id: uuid(),
        item: "PHONE CASE",
        category: "love_myself",
        price: "25.00",
        src: "phone_case_lm",
        description: "SIZE:\n56 X 125\n\nMATERIAL:\nPOLYCARBONATE / PU / METAL\n\nMADE IN KOREA",
        stock: "1000",
        shipping: "2.00",
        freeShipping: "30.00",
        soldQ: "0"
    }
];

export default productsArray;